import { SolfeggioFrequency } from './types';

export const SOLFEGGIO_FREQUENCIES: SolfeggioFrequency[] = [
  {
    id: '174',
    frequency: 174,
    name: 'Pain & Stress Relief',
    description: 'The lowest of the tones, 174 Hz acts like a natural anesthetic. It is excellent for relieving pain and reducing stress.',
    color: 'bg-stone-700/30',
    hoverColor: 'hover:bg-stone-600/40',
    glowColor: '#a8a29e',
    textColor: 'text-stone-100',
  },
  {
    id: '285',
    frequency: 285,
    name: 'Tissue & Organ Healing',
    description: 'This frequency is believed to influence energy fields, helping to heal tissues and organs by sending a message to restructure damaged areas.',
    color: 'bg-amber-800/30',
    hoverColor: 'hover:bg-amber-700/40',
    glowColor: '#f59e0b',
    textColor: 'text-amber-100',
  },
  {
    id: '396',
    frequency: 396,
    name: 'Liberating Guilt & Fear',
    description: 'Associated with the Root Chakra, this frequency helps in grounding, cleansing feelings of guilt, and turning grief into joy.',
    color: 'bg-red-700/30',
    hoverColor: 'hover:bg-red-600/40',
    glowColor: '#f87171',
    textColor: 'text-red-100',
  },
  {
    id: '417',
    frequency: 417,
    name: 'Facilitating Change',
    description: 'Connected to the Sacral Chakra, 417 Hz helps to undo challenging situations and facilitate positive change by clearing traumatic experiences.',
    color: 'bg-orange-600/30',
    hoverColor: 'hover:bg-orange-500/40',
    glowColor: '#fb923c',
    textColor: 'text-orange-100',
  },
  {
    id: '528',
    frequency: 528,
    name: 'Transformation & Miracles',
    description: 'Known as the "love frequency," it is associated with DNA repair, increased energy, clarity of mind, and achieving one\'s highest purpose.',
    color: 'bg-yellow-500/30',
    hoverColor: 'hover:bg-yellow-400/40',
    glowColor: '#facc15',
    textColor: 'text-yellow-100',
  },
  {
    id: '639',
    frequency: 639,
    name: 'Connecting Relationships',
    description: 'Linked with the Heart Chakra, this frequency enhances communication, understanding, tolerance, and love, helping to heal relationships.',
    color: 'bg-green-600/30',
    hoverColor: 'hover:bg-green-500/40',
    glowColor: '#4ade80',
    textColor: 'text-green-100',
  },
  {
    id: '741',
    frequency: 741,
    name: 'Awakening Intuition',
    description: 'The tone of the Throat Chakra, 741 Hz is used for cleansing toxins from the body and for promoting self-expression and awakening intuition.',
    color: 'bg-cyan-600/30',
    hoverColor: 'hover:bg-cyan-500/40',
    glowColor: '#22d3ee',
    textColor: 'text-cyan-100',
  },
  {
    id: '852',
    frequency: 852,
    name: 'Returning to Spirit',
    description: 'Associated with the Third Eye Chakra, this frequency helps to see through illusions, awaken intuition, and return to spiritual order.',
    color: 'bg-indigo-700/30',
    hoverColor: 'hover:bg-indigo-600/40',
    glowColor: '#818cf8',
    textColor: 'text-indigo-100',
  },
  {
    id: '963',
    frequency: 963,
    name: 'Divine Consciousness',
    description: 'The frequency of the Crown Chakra, 963 Hz connects us to the oneness of the universe, awakening any system to its original, perfect state.',
    color: 'bg-purple-700/30',
    hoverColor: 'hover:bg-purple-600/40',
    glowColor: '#c084fc',
    textColor: 'text-purple-100',
  },
];